language: dart
sudo: false
dart:
  - 1.20.0-dev.1.0
  - 1.20.0-dev.3.0
  - 1.20.0-dev.4.0
  - 1.20.0-dev.5.0
  - 1.20.0-dev.7.0
  - 1.20.0-dev.9.0
  - 1.20.0-dev.10.0
  - 1.20.0-dev.10.1
  - 1.20.0-dev.10.2
  - 1.20.0-dev.10.3
  - 1.20.1
  - 1.19.1
cache:
  directories:
    - $HOME/.pub-cache
with_content_shell: true
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 't=0; until (xdpyinfo -display :99 &> /dev/null || test $t -gt 10); do sleep 1; let t=$t+1; done'
script: pub run test -p content-shell,firefox
